from pydantic import BaseModel
class UserCreate(BaseModel):
    name: str
    email: str
    password: str
class User(BaseModel):
    id: int
    name: str
    email: str
class HotelCreate(BaseModel):
    name: str
    city: str
description: Optional[str]
rating: Optional[float]
class Hotel(BaseModel):
    id: int
    name: str
    city: str
description: Optional[str]
rating: Optional[float]
class RoomCreate(BaseModel):
    hotel_id: int
type: str
price: float
capacity: int
availability_count: int
class Room(BaseModel):
    id: int
    hotel_id: int
type: str
price: float
capacity: int
availability_count: int
class BookingCreate(BaseModel):
    user_id: int
room_id: int
check_in: datetime
check_out: datetime
price: float
status: str
class Booking(BaseModel):
    id: int
    user_id: int
room_id: int
check_in: datetime
check_out: datetime
price: float
status: str